---
config:
  layout: elk
---
erDiagram
    %% ============================================================
    %% Familia 4: Vocabulario Clinico
    %% ============================================================

    SNOMED_BODY_STRUCTURE {
        string SnomedCode PK
        string BodyRegionCode FK
        string DisplayName
        string StructureType
        string ParentStructureCode FK
        string Description
        bool IsActive
        timestamp CreatedAt
        timestamp UpdatedAt
    }

    SNOMED_BODY_REGION {
        string SnomedCode PK
        string DisplayName
        string ParentRegionCode FK
        string Description
        bool IsActive
        timestamp CreatedAt
        timestamp UpdatedAt
    }

    SNOMED_TOPOGRAPHICAL_MODIFIER {
        string Code PK
        string DisplayName
        string Category
        string Description
        bool IsActive
        timestamp CreatedAt
        timestamp UpdatedAt
    }

    CLINICAL_CONDITION {
        string SnomedCode PK
        string DisplayName
        string Description
        bool IsActive
        timestamp CreatedAt
        timestamp UpdatedAt
    }

    VOLUNTEER_CLINICAL_CONDITION {
    }

    TARGET_AREA_TOPOGRAPHICAL_MODIFIER {
        uuid TargetAreaId FK
        string TopographicalModifierCode FK
    }


    TARGET_AREA { }

    %% Relacionamentos internos
    %% Hierarquia auto-referencial expressa via FK ParentRegionCode / ParentStructureCode
    SNOMED_BODY_STRUCTURE ||--o| SNOMED_BODY_REGION : pertence

    %% Relacionamentos com outras familias

    CLINICAL_CONDITION ||--o{  VOLUNTEER_CLINICAL_CONDITION: "é possuida por"
    TARGET_AREA ||--|| SNOMED_BODY_STRUCTURE : refere
    TARGET_AREA ||--o{  TARGET_AREA_TOPOGRAPHICAL_MODIFIER : "referida por"
    SNOMED_TOPOGRAPHICAL_MODIFIER ||--o{TARGET_AREA_TOPOGRAPHICAL_MODIFIER : "referida por"