---
config:
  layout: elk
---
erDiagram
    RESEARCH {}
    VOLUNTEER {}

    RESEARCH_NODE {
        uuid Id PK
        string NodeName
        string Certificate
        string CertificateFingerprint
        string NodeUrl
        string Status
        string NodeAccessLevel
        string ContactInfo
        string InstitutionDetails
        timestamp RegisteredAt
        timestamp UpdatedAt
        timestamp LastAuthenticatedAt
        jsonb Metadata
    }

    USER {
        uuid Id PK
        string Login
        string PasswordHash
        string Role
        timestamp CreatedAt
        timestamp UpdatedAt
    }

    RESEARCHER {
        uuid ResearcherId PK
        uuid ResearchNodeId FK
        string Name
        string Email
        string Institution
        string Role
        string Orcid
        timestamp CreatedAt
        timestamp UpdatedAt
    }

    SYNC_LOG {
        uuid Id PK
        uuid RemoteNodeId FK
        timestamp StartedAt
        timestamp CompletedAt
        string Status
        timestamp LastSyncedAt
        string EntitiesReceived
        string ErrorMessage
    }

    %% Relacionamentos internos
    USER ||--|| RESEARCHER : autentica
    RESEARCH_NODE ||--o{ SYNC_LOG : registra
    RESEARCH_NODE ||--o{ RESEARCHER : hospeda

    %% Relacionamentos com outras familias
    VOLUNTEER }o--|| RESEARCH_NODE : hospeda
    RESEARCH }o--||  RESEARCH_NODE : hospeda
